output "cluster_id" {
  description = "Cluster identifier (e.g. `strata-dev`). Use with `aws rds describe-db-clusters --db-cluster-identifier`."
  value       = aws_rds_cluster.aurora.id
}

output "cluster_arn" {
  description = "ARN of the Aurora cluster. Use to scope IAM permissions and CloudWatch alarms."
  value       = aws_rds_cluster.aurora.arn
}

output "cluster_resource_id" {
  description = "AWS-internal cluster resource ID (e.g. `cluster-XXXXXXXX`). Required for IAM database authentication grants (`rds-db:connect`) — the rds-db ARN format embeds this, not the cluster_id."
  value       = aws_rds_cluster.aurora.cluster_resource_id
}

output "cluster_endpoint" {
  description = "Writer endpoint (DNS) of the Aurora cluster. Direct cluster access — typically NOT what consumers use; see proxy_endpoint instead. Useful for migration tooling and `psql` operator access."
  value       = aws_rds_cluster.aurora.endpoint
}

output "cluster_reader_endpoint" {
  description = "Reader endpoint of the Aurora cluster. Round-robins across reader instances (none in dev when instance_count = 1; in that case it returns the writer's address). Use for read-heavy workloads when the consumer can split reads/writes."
  value       = aws_rds_cluster.aurora.reader_endpoint
}

output "cluster_port" {
  description = "TCP port the cluster listens on. Always 5432 for Postgres; emitted as an output for symmetry."
  value       = aws_rds_cluster.aurora.port
}

output "database_name" {
  description = "Initial database name created on cluster bootstrap."
  value       = aws_rds_cluster.aurora.database_name
}

output "master_username" {
  description = "Master DB user name. The password is auto-generated by AWS and stored in master_user_secret_arn."
  value       = aws_rds_cluster.aurora.master_username
}

output "master_user_secret_arn" {
  description = "ARN of the AWS-managed Secrets Manager secret holding the master credential. AWS rotates this on a managed schedule. Consumers attach `consumer_iam_policy_json` to read it; RDS Proxy reads it transparently. Plaintext is never an output."
  value       = aws_rds_cluster.aurora.master_user_secret[0].secret_arn
}

output "master_user_secret_kms_key_id" {
  description = "KMS key ID encrypting the auto-managed master credential secret. Same key as kms_key_arn — emitted as a separate output for clarity when wiring consumer IAM grants."
  value       = aws_rds_cluster.aurora.master_user_secret[0].kms_key_id
}

output "proxy_endpoint" {
  description = "RDS Proxy endpoint hostname. THIS is the value consumers put in DATABASE_URL. Connection string shape: `postgres://{master_username}:{password}@{proxy_endpoint}:5432/{database_name}?sslmode=require`. Master username + password are read from master_user_secret_arn at runtime."
  value       = aws_db_proxy.aurora.endpoint
}

output "proxy_arn" {
  description = "ARN of the RDS Proxy. Use to scope IAM permissions for proxy management (CloudWatch alarms, target group inspection)."
  value       = aws_db_proxy.aurora.arn
}

output "proxy_name" {
  description = "Name of the RDS Proxy (e.g. `strata-dev-proxy`). Useful for `aws rds describe-db-proxy-targets --db-proxy-name`."
  value       = aws_db_proxy.aurora.name
}

output "kms_key_arn" {
  description = "ARN of the per-cluster KMS CMK encrypting cluster storage, Performance Insights data, and the master credential secret. Consumers grant `kms:Decrypt` on this ARN to read the secret."
  value       = aws_kms_key.aurora.arn
}

output "kms_key_alias" {
  description = "Alias of the per-cluster CMK. Format: `alias/strata-{env}-aurora`."
  value       = aws_kms_alias.aurora.name
}

output "security_group_id" {
  description = "ID of the security group attached to the cluster + proxy ENIs. Consumers SHOULD add their own egress rule allowing TCP/5432 to this SG, then pass their consumer SG ID into this module via `var.allowed_security_group_ids` so ingress is mutually scoped."
  value       = aws_security_group.cluster.id
}

output "subnet_group_name" {
  description = "Name of the DB subnet group spanning the isolated subnets. Useful when other RDS resources (read replicas, restored snapshots) need to land in the same subnet group."
  value       = aws_db_subnet_group.aurora.name
}

output "parameter_group_name" {
  description = "Name of the cluster parameter group preloading pg_stat_statements. Useful for adding cluster-level Postgres parameters out-of-band."
  value       = aws_rds_cluster_parameter_group.aurora.name
}

output "consumer_iam_policy_json" {
  description = "Least-privilege IAM policy JSON granting `secretsmanager:GetSecretValue` on the master credential secret + `kms:Decrypt` on the cluster CMK (scoped via kms:ViaService). Attach to consumer task roles. Network reachability (egress 5432 to the cluster SG) is the consumer's separate responsibility."
  value       = data.aws_iam_policy_document.consumer.json
}
