/**
 * LLM-powered session summarizer.
 *
 * Generates structured summaries using an LLM provider, falling back
 * to the heuristic summarizer on any failure.
 *
 * Training data capture: after a successful LLM summarization, the
 * (prompt, output) pair is saved for local model distillation.
 */

import type { ParsedSession } from "../../parsers/session-parser.js";
import {
  summarizeSession,
  type SessionSummary,
} from "../../knowledge/session-summarizer.js";
import type { LlmProvider } from "./llm-provider.js";
import { saveTrainingPair } from "./training-capture.js";
import type Database from "better-sqlite3";

/** Extended summary with LLM-extracted fields */
export interface SmartSummary extends SessionSummary {
  /** Concise description of the session's main topic */
  topicSummary: string;
  /** Key decisions made during the session */
  keyDecisions: string[];
  /** Solutions discovered or applied */
  solutionsFound: string[];
  /** Recurring patterns observed */
  patterns: string[];
  /** Actionable takeaways */
  actionableLearnings: string[];
  /** Whether this summary was generated by LLM */
  llmGenerated: boolean;
}

/** Structured output from the LLM prompt */
interface LlmSummaryOutput {
  topic: string;
  keyDecisions: string[];
  solutionsFound: string[];
  patterns: string[];
  actionableLearnings: string[];
}

const SUMMARIZER_PROMPT = `You are analyzing a coding assistant conversation session. Extract structured knowledge from the conversation.

Return ONLY valid JSON with this exact structure (no markdown, no explanation):
{
  "topic": "One sentence describing what this session was about",
  "keyDecisions": ["Decision 1", "Decision 2"],
  "solutionsFound": ["Solution 1", "Solution 2"],
  "patterns": ["Pattern 1"],
  "actionableLearnings": ["Learning 1", "Learning 2"]
}

Rules:
- topic: Brief (under 100 chars), specific description
- keyDecisions: Architectural or implementation choices made. Empty array if none.
- solutionsFound: Bugs fixed, problems solved. Include the problem and solution. Empty array if none.
- patterns: Reusable approaches or anti-patterns discovered. Empty array if none.
- actionableLearnings: Concrete takeaways someone could apply in future work. Empty array if none.
- Each array item should be a concise sentence (under 120 chars).
- Maximum 5 items per array.

Session transcript:
`;

/**
 * Generate a smart summary using an LLM provider.
 *
 * Falls back to heuristic summary on any LLM failure.
 *
 * @param session - Parsed session data
 * @param provider - LLM provider to use
 * @param db - Optional database for training data capture
 */
export async function smartSummarize(
  session: ParsedSession,
  provider: LlmProvider,
  db?: Database.Database
): Promise<SmartSummary> {
  // Always generate the heuristic base
  const base = summarizeSession(session);

  try {
    const transcript = formatTranscript(session);
    const prompt = SUMMARIZER_PROMPT + transcript;

    const raw = await provider.complete(prompt, {
      maxTokens: 4096,
      temperature: 0.1,
      timeoutMs: 30000,
    });

    const parsed = parseJsonResponse(raw);

    const result: SmartSummary = {
      ...base,
      topicSummary: parsed.topic || base.topic,
      keyDecisions: parsed.keyDecisions || [],
      solutionsFound: parsed.solutionsFound || [],
      patterns: parsed.patterns || [],
      actionableLearnings: parsed.actionableLearnings || [],
      llmGenerated: true,
    };

    // Training data capture (Task 6) — NEVER affects primary path
    if (db && parsed.topic) {
      try {
        saveTrainingPair(db, {
          taskType: "summarization",
          inputText: prompt,
          outputJson: raw,
          modelUsed: provider.name,
          qualityScore: 1.0,
          heuristicDiverged: false,
        });
      } catch (captureErr) {
        // Swallow — training capture must never affect summarization
        console.warn("[training-capture] summarization capture failed:", captureErr);
      }
    }

    return result;
  } catch {
    // Fallback to heuristic summary
    return heuristicSmartSummary(base);
  }
}

/**
 * Create a SmartSummary from heuristic-only data (fallback).
 */
export function heuristicSmartSummary(base: SessionSummary): SmartSummary {
  return {
    ...base,
    topicSummary: base.topic,
    keyDecisions: [],
    solutionsFound: [],
    patterns: [],
    actionableLearnings: [],
    llmGenerated: false,
  };
}

/**
 * Format session messages into a compact transcript for the LLM.
 * Truncates to fit within ~1500 tokens to keep total prompt under 2000 tokens.
 */
function formatTranscript(session: ParsedSession): string {
  const lines: string[] = [];
  let charBudget = 6000; // ~1500 tokens at ~4 chars/token

  for (const msg of session.messages) {
    if (charBudget <= 0) break;
    const prefix = msg.role === "user" ? "USER" : "ASSISTANT";
    const text = msg.text.slice(0, Math.min(msg.text.length, 300));
    const line = `[${prefix}] ${text}`;
    lines.push(line);
    charBudget -= line.length;
  }

  return lines.join("\n");
}

/**
 * Parse JSON from LLM response, handling markdown code fences.
 */
function parseJsonResponse(raw: string): LlmSummaryOutput {
  const cleaned = extractJson(raw);
  const parsed = JSON.parse(cleaned) as LlmSummaryOutput;

  // Validate structure
  if (typeof parsed.topic !== "string") {
    throw new Error("Invalid summary: missing topic");
  }

  // Ensure arrays
  parsed.keyDecisions = Array.isArray(parsed.keyDecisions) ? parsed.keyDecisions.slice(0, 5) : [];
  parsed.solutionsFound = Array.isArray(parsed.solutionsFound) ? parsed.solutionsFound.slice(0, 5) : [];
  parsed.patterns = Array.isArray(parsed.patterns) ? parsed.patterns.slice(0, 5) : [];
  parsed.actionableLearnings = Array.isArray(parsed.actionableLearnings) ? parsed.actionableLearnings.slice(0, 5) : [];

  return parsed;
}

/**
 * Extract JSON from LLM response, handling markdown fences and preamble text.
 * Gemini 2.5+ models may include thinking/reasoning text before the JSON.
 */
function extractJson(raw: string): string {
  let text = raw.trim();

  // Strip markdown code fences
  if (text.includes("```")) {
    const fenced = text.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
    if (fenced) return fenced[1].trim();
  }

  // Try parsing directly first
  if (text.startsWith("{") || text.startsWith("[")) {
    return text;
  }

  // Find first { and last } to extract embedded JSON
  const firstBrace = text.indexOf("{");
  const lastBrace = text.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace > firstBrace) {
    return text.slice(firstBrace, lastBrace + 1);
  }

  return text;
}
